name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install gfortran libmotif-dev
        sudo apt-get install python3-matplotlib
        sudo apt-get install openmpi-bin libopenmpi-dev
        sudo apt-get install texlive texlive-latex-extra transfig
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew reinstall gfortran
        brew install qt@5 openmotif open-mpi coin3d
        brew link qt@5 --force
        brew install basictex fig2dev
        eval "$(/usr/libexec/path_helper)"
        sudo tlmgr update --self
        sudo tlmgr update --all
        sudo tlmgr install moreverb subfigure
        brew install python-tk
        pip install matplotlib
        pip3 install matplotlib
    - name: Install packages for Ubuntu 18.04 only
      if: matrix.os == 'ubuntu-18.04'
      run: sudo apt-get install libsoqt4-dev python-matplotlib
    - name: Install packages for Ubuntu 20.04 only
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get install libsoqt520-dev python-tk python-numpy
    - name: Compile
      run: |
        # compile auto
        ./configure --enable-gui --with-mpi
        make
        # compile manual
        if [ "$RUNNER_OS" == "macOS" ]; then
          eval "$(/usr/libexec/path_helper)"
        fi
        make -C doc auto.pdf ../plaut04/doc/userguide.pdf
    - name: Run test (python2)
      run: |
        export OMPI_MCA_btl="^openib"
        cd test
        python2 ../python/auto all.auto
        mv *_log07p python2log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python2log
        path: test/python2log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python2verification
        path: test/verification
    - name: Run test (python3)
      run: |
        export OMPI_MCA_btl="^openib"
        cd test
        python3 ../python/auto all.auto
        mv *_log07p python3log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python3log
        path: test/python3log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python3verification
        path: test/verification
    - name: Run test (MPI + python3)
      if: runner.os == 'Linux'
        run: |
          export AUTO_COMMAND_PREFIX="mpirun -n 2"
          export OMP_NUM_THREADS=1
          export OMPI_MCA_btl="^openib"
          cd test
          python3 ../python/auto all.auto
          mv *_log07p python3mpilog.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python3mpilog
        path: test/python3mpilog.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python3mpiverification
        path: test/verification
