name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gfortran libsoqt4-dev libmotif-dev
        sudo apt-get install python-matplotlib python3-matplotlib
        sudo apt-get install openmpi-bin libopenmpi-dev
        sudo apt-get install texlive texlive-latex-extra transfig
    - name: Compile
      run: |
        # compile auto
        ./configure --enable-gui --with-mpi
        make
        # compile manual
        make -C doc auto.pdf ../plaut04/doc/userguide.pdf
    - name: Run test (python2)
      run: |
        export OMPI_MCA_btl="^openib"
        cd test
        python2 ../python/auto all.auto
        mv *_log07p python2log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python2log
        path: test/python2log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python2verification
        path: test/verification
    - name: Run test (python3)
      run: |
        export OMPI_MCA_btl="^openib"
        cd test
        python3 ../python/auto all.auto
        mv *_log07p python3log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python3log
        path: test/python3log.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python3verification
        path: test/verification
    - name: Run test (MPI + python3)
      run: |
        export AUTO_COMMAND_PREFIX="mpirun -n 2"
        export OMP_NUM_THREADS=1
        export OMPI_MCA_btl="^openib"
        cd test
        python3 ../python/auto all.auto
        mv *_log07p python3mpilog.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python3mpilog
        path: test/python3mpilog.txt
    - uses: actions/upload-artifact@v1
      with:
        name: python3mpiverification
        path: test/verification
